#kubectl run n1 --image=nginx --port=80
#kubectl expose pod n1 --name=n1svc --port=80 --target-port=80 --type=NodePort
apiVersion: v1
kind: Namespace
metadata:
  name: dev
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: web
#   labels:
#     app: web
#   namespace: dev
# spec:
#   containers:
#   - name: web
#     image: "devopsjuly22017/web:latest"
#     ports:
#     - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
  namespace: dev
spec:
  replicas: 3
  selector:
    selector:
      matchLabels:
        app: web
  template:
    metadata:
      name: web
      labels:
        app: web
       namespace: dev
    spec:
      containers:
      - name: web
        image: "devopsjuly22017/web:latest"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: websvc
  namespace: dev
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
  namespace: dev
spec:
  containers:
  - name: redis
    image: "redis:alpine"
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dev
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379