# https://eksctl.io/getting-started/
# eksctl create cluster -f cluster.yml
# eksctl delete cluster -f cluster.yml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1
  zones: us-east-1c, us-east-1f

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.micro
    desiredCapacity: 2
  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 1